---
- name: "Start the filter_band config!"
  hosts: sprawl_nodes
  gather_facts: false

  tasks:
    - name: Kill all Scyclone processes
      command:
        cmd: killall Scyclone
      ignore_errors: yes

    - name: "Kill SC!"
      shell: killall sclang
      ignore_errors: true

    - name: "Kill SC!"
      shell: killall scsynth
      ignore_errors: true
