---
- name: "Rollout Scyclone Binaries"
  hosts: sprawl_nodes_no_video_node
  gather_facts: false

  tasks:
    - name: Determine Scyclone model
      set_fact:
        scyclone_model: >-
          {{
            'Cats' if scyclone_id == '0' else
            'VCTK' if scyclone_id == '1' else
            'Jazz' if scyclone_id == '2' else
            'Djembe' if scyclone_id == '3' else
            'Cats'
          }}
      vars:
        scyclone_id: '1'                                        # Sprache
        # scyclone_id: '0'                                        # Katze
        # scyclone_id: '2'                                        # Jazz (Jazz) Jazz!
        # scyclone_id: "{{ (inventory_hostname[-2:] | int)  % 4 }}" # Gemischt

    - name: Debug
      debug: 
        msg: "{{ scyclone_model }}"

    - name: "Ensure 'pieces' dir exists"
      copy:
        src: "binaries/Scyclone_{{ scyclone_model }}"
        dest: /home/member/pieces/Scyclone
        owner: member
        group: member
        mode: '0755'

    - name: "Copy Files onto the server"
      copy:
        src: binaries/libonnxruntime.so.1.12.1
        dest: /usr/lib/libonnxruntime.so.1.12.1
        owner: root
        group: root
        mode: '0755'
      become: true

    - name: Kill all Scyclone processes
      command:
        cmd: killall Scyclone
      ignore_errors: yes
      
    - name: Start Scyclone
      async: 2592000 # run for 1 month
      poll: 0
      shell: DISPLAY=:0 /home/member/pieces/Scyclone >> /tmp/ScycloneLog.txt

    - name: Wait for Scyclone to Start
      ansible.builtin.shell: jack_lsp
      register: result
      until: result.stdout.find("Scyclone:out_1") != -1
      retries: 30
      delay: 1