---
- name: "Start the filter_band config!"
  hosts: sprawl_nodes_no_video_node
  gather_facts: false

  tasks:
    - name: "Connect all Supercollider Instances to Hardware In- and Outputs"
      ansible.builtin.shell: |
        jack_connect Distributor:out_1 system:playback_1
        jack_connect system:capture_1 Scyclone:in_1
        jack_connect system:capture_2 Scyclone:in_1
        jack_connect Scyclone:out_1 Distributor:in_1
        jack_connect Scyclone:out_2 Distributor:in_1
      vars:
        length_of_hosts: "{{ ansible_play_hosts | length }}"

    - name: "Connect Jacktrip Clients"
      ansible.builtin.shell: |
        jack_connect Distributor:out_{{ index + 2 }} {{ peer }}:send_1
        jack_connect {{ peer }}:receive_1 Scyclone:in_1
      vars:
        index:
          "{{ ansible_play_hosts.index(inventory_hostname) }}"
          # rotates the list of hosts, (index | int) to convert the index back to int
        rotated_host_list: "{{ ansible_play_hosts[(index | int):] + ansible_play_hosts[:(index | int)] }}"
      loop: "{{ rotated_host_list[1:] }}"
      loop_control:
        index_var: index
        loop_var: peer