---
- name: Start Distributor
  hosts: sprawl_nodes_no_video_node
  gather_facts: true
  tasks:
    - name: "Kill SC!"
      shell: killall sclang
      ignore_errors: true

    - name: "Kill SC!"
      shell: killall scsynth
      ignore_errors: true

    - name: "Ensure 'pieces' dir exists"
      ansible.builtin.file:
        path: /home/member/pieces/
        state: directory
        owner: member
        group: member
        mode: "u=rwx,g=rx,o=rx"

    - name: "Copy Files onto the server"
      ansible.builtin.copy:
        src: ../distribution/SC
        dest: /home/member/pieces/distributor
        owner: member
        group: member
        mode: "0644"

    - name: "Launch SC!"
      async: 2592000 # run for 1 month
      poll: 0
      # n_hosts - 1 is the number of peers
      shell: DISPLAY=:0 sclang distributor.scd {{ n_hosts }} > /tmp/distributor.log
      args:
        chdir: /home/member/pieces/distributor/SC
      vars:
        n_hosts: "{{ ansible_play_hosts | length }}"

    - name: Wait for Supercollider to Start
      ansible.builtin.shell: jack_lsp
      register: result
      until: result.stdout.find("Distributor:out_1") != -1
      retries: 30
      delay: 1
