---
- name: Start fully connected Jacktrip Mesh
  hosts: sprawl_nodes
  gather_facts: false

  tasks:

    - name: "Connect ins/outs"
      ansible.builtin.shell: |
        jack_connect {{item}}:receive_1 SuperCollider:in_1
        jack_connect SuperCollider:out_1 system:playback_1
        jack_connect system:capture_1  {{item}}:send_1
      loop: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
      loop_control:
        index_var: index

  vars:
    base_port: 4464
