---
- name: Start Supercollider
  hosts: sprawl_nodes
  gather_facts: false
  tasks:
    - name: "Ensure 'pieces' dir exists"
      ansible.builtin.file:
        path: /home/member/pieces/
        state: directory
        owner: member
        group: member
        mode: "u=rwx,g=rx,o=rx"

    - name: "Copy Files onto the server"
      copy:
        src: SC
        dest: /home/member/pieces/tvstud/
        owner: member
        group: member
        mode: "0644"

    - name: "Launch SC!"
      async: 2592000 # run for 1 month
      poll: 0
      shell: DISPLAY=:0 sclang main.scd >> /tmp/tvstud.log
      args:
        chdir: /home/member/pieces/tvstud/SC

- name: "Sleepytime"
  hosts: localhost
  gather_facts: false
  tasks:
    - name: GuNa
      ansible.builtin.wait_for:
        timeout: 3

- name: Setup Jack Connections
  hosts: sprawl_nodes
  gather_facts: false
  tasks:
    - name: Connect local ins/outs
      shell: |
        jack_connect system:capture_1 SuperCollider:in_1
        jack_connect SuperCollider:out_1 system:playback_1


