---
- name: "Remove the filter_band config!"
  hosts: sprawl_nodes
  gather_facts: false
  tasks:
    - name: "Kill SC!"
      shell: killall sclang
      ignore_errors: true

    - name: "Kill SC!"
      shell: killall scsynth
      ignore_errors: true

    - name: "Kill JackTrip!"
      shell: killall jacktrip
      ignore_errors: true
