---
- name: Start fully connected Jacktrip Mesh
  hosts: sprawl_nodes
  gather_facts: false
  tasks:
    - name: Kill all JackTrip things
      command: killall jacktrip
      ignore_errors: true

    - name: "Launch JackTrip Server"
      shell: jacktrip -S -p5
      async: 2592000 # run for 1 month
      poll: 0

    - name: "Launch lots of JackTrip clients"
      # create connection to server with the name
      shell: jacktrip -n 1 -C {{ item }} -K {{ inventory_hostname }} -J {{ item }} -B {{ base_port + index }}
      async: 2592000 # run for 1 month
      poll: 0
      loop: "{{ ansible_play_hosts | difference([inventory_hostname]) }}"
      loop_control:
        index_var: index
      when: index < ansible_play_hosts.index(inventory_hostname)

  vars:
    base_port: 4464
