---
- name: Install_ssh_key
  hosts: sprawl_nodes
  connection: ssh

  tasks:
    - name: Install public SSH key
      ansible.posix.authorized_key:
        user: member
        state: present
        key: "{{ lookup('file', key) }}"
