---
- name: Restart jackd
  hosts: sprawl_nodes
  gather_facts: false
  become: true
  become_method: sudo

  tasks:
    - name: Template out jackd.service

      ansible.builtin.template:
        src: jackd.service.j2
        dest: /usr/lib/systemd/user/jackd.service
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      vars:
        jackd_params: -R -a a -d alsa -d hw:CODEC -p 128

    # - name: Reload systemd daemon
    #   ansible.builtin.systemd:
    #     daemon_reload: true

    - name: Restart jackd service
      ansible.builtin.systemd:
        daemon_reload: true
        service: jackd.service
        state: restarted
        scope: user
      become: false
